name: sirat_e_mustaqeem
description: Flutter prject for Muslim brothers
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  dio: ^4.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_local_notifications: ^8.1.1+1
  flutter_native_timezone: ^2.0.0
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  geolocator: ^7.4.0
  google_fonts: ^2.1.0
  hydrated_bloc: ^7.0.1
  intl: ^0.17.0
  json_annotation: ^4.1.0
  lottie: ^1.1.0
  motion_sensors: ^0.1.0
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  sqflite: ^2.0.0+3

dev_dependencies:
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^5.0.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/core/json/
    - assets/navigation_icon/svg/
    - assets/home_icon/svg/
    - assets/collection_icon/svg/
    - assets/qiblat_icon/svg/
    - assets/praying_time/svg/
    - assets/setting_icon/svg/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
